import React from 'react';
import { createRoot } from 'react-dom/client';
import './palette.css';
import '@fontsource/dm-sans/400.css';
import '@fontsource/dm-sans/500.css';
import '@fontsource/dm-sans/600.css';
import '@fontsource/dm-sans/700.css';
import '@fontsource/newsreader/400.css';
import '@fontsource/newsreader/500.css';
import '@fontsource/newsreader/400-italic.css';
import Landing from './Landing';
createRoot(document.getElementById('root')!).render(<React.StrictMode><Landing/></React.StrictMode>);
